apiVersion: v1
kind: Template
labels:
  template: redis-cache
metadata:
  annotations:
    description: >
      Redis is an open source key-value store that functions as a data structure server.
      This template provides a memory-only instance, recomended when Redis acts as a
      cache and it's ok to lose data during service restarts.
    iconClass: icon-redis
    tags: cache,database,redis
  creationTimestamp: null
  name: redis-cache

objects:
- kind: Service
  apiVersion: v1
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    portalIP: ""
    ports:
    - name: tcp
      nodePort: 0
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      name: ${NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    creationTimestamp: null
    name: ${NAME}
    labels:
      name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: ${NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: REDIS_DIR
            value: ${REDIS_DIR}
          - name: REDIS_DBFILENAME
            value: ${REDIS_DBFILENAME}
          - name: REDIS_MAX_MEMORY
            value: ${REDIS_MAX_MEMORY}
          - name: REDIS_MAX_MEMORY_POLICY
            value: ${REDIS_MAX_MEMORY_POLICY}
          - name: REDIS_EXTRA_PARAMETERS
            value: ${REDIS_EXTRA_PARAMETERS}
          image: docker.io/getupcloud/redis:${REDIS_VERSION}
          imagePullPolicy: IfNotPresent
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          resources: {}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis
        from:
          kind: ImageStreamTag
          name: redis:${REDIS_VERSION}
          namespace: openshift
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}

parameters:
- description: Redis service name
  name: NAME
  required: true
  value: "redis-cache"
- description: Max memory Redis can use
  name: REDIS_MAX_MEMORY
  required: false
  value: ""
- description: How Redis will select what to remove when maxmemory is reached
  name: REDIS_MAX_MEMORY_POLICY
  required: false
  value: "allkeys-lru"
- description: Extra command line parameters to start redis
  name: REDIS_EXTRA_PARAMETERS
  required: false
  value: "--maxclients 5000 --tcp-backlog 128"
- description: Filename for database save operations
  name: REDIS_DBFILENAME
  required: false
  value: "database.rdb"
- description: Dirname of file on save operations
  name: REDIS_DIR
  required: false
  value: "/tmp/redis"
- description: Redis version
  displayName: Redis version [select:3.0=3.0:3.2=3.2:4.0=4.0]
  name: REDIS_VERSION
  required: true
  value: "3.2"
